# GitHub Actions Workflow for building with GCC and Clang

name: CMake Multi-Compiler Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The job will run on the latest version of Ubuntu
    runs-on: ubuntu-latest

    # Define a build matrix to test against different compilers
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release]
        include:
          - os: ubuntu-latest
            c_compiler: gcc-14
            cpp_compiler: g++-14
          - os: ubuntu-latest
            c_compiler: clang-18
            cpp_compiler: clang++-18

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
   
    - name: Install Dependencies and Compiler
      run: |
        sudo apt-get update
        
        if [ "${{ matrix.c_compiler }}" = "gcc-14" ]; then
          # Add the toolchain PPA to get access to newer GCC versions
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y g++-14 
        elif [ "${{ matrix.c_compiler.name }}" = "clang-18" ]; then
          # Use the official LLVM script to install a specific Clang version
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18
          sudo apt-get install -y clang-18
        fi
    - name: Install libuv
      run: |
        wget https://github.com/libuv/libuv/archive/refs/tags/v1.49.2.tar.gz
        tar -xvzf v1.49.2.tar.gz
        cd libuv-1.49.2
        sh autogen.sh
        ./configure
        make
        make check
        sudo make install
        
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory.
      # We explicitly pass the C and C++ compilers to CMake.
      run: >
        cmake -B ${{github.workspace}}/build
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DCMAKE_C_COMPILER=${{matrix.c_compiler}}
        -DCMAKE_CXX_COMPILER=${{matrix.cpp_compiler}}

    - name: Build Project
      # Build your program with the configuration specified in the matrix
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Run Tests
      # Execute tests defined by the CMake configuration
      working-directory: ${{github.workspace}}/build/tests
      run: ctest -C ${{env.BUILD_TYPE}}
